Repository actions/runner-images, pull requests merged in 2020-01, with the labels that each got.

#211 Don't bloat the PATH when installing git
  images/win/scripts/Installers/Install-Git.ps1
Labels: Area: Git

#261 Fix incorrect display Clang 6.0 version in Ubuntu-README.md
  images/linux/Ubuntu1604-README.md
  images/linux/Ubuntu1804-README.md
  images/linux/scripts/installers/clang.sh
Labels: Area: Scripting and command line, bug

#276 Add -Install to Get-WUInstall call to actually install Windows Updates.
  images/win/scripts/Installers/Install-WindowsUpdates.ps1
Labels: bug

#179 Update to Kind v0.7.0
  images/linux/scripts/installers/kind.sh
  images/win/scripts/Installers/Install-Kind.ps1
Labels: Area: Containers, enhancement

#340 Increase max number of open files
  images/linux/ubuntu1604.json
  images/linux/ubuntu1804.json
Labels: OS: Ubuntu, bug

#341 Add libmysqlclient-dev installation on Ubuntu
  images/linux/scripts/installers/mysql.sh
Labels: Area: Databases, OS: Ubuntu, bug
